components:
  parameters:
    DateFrom:
      name: date_from
      in: query
      description: "Return only objects that have last_updated after this date/time. See OCPI Spec 2.2.1."
      required: false
      schema:
        $ref: '../common/definitions.yaml#/components/schemas/DateTime'
    
    DateTo:
      name: date_to
      in: query
      description: "Return only objects that have last_updated before this date/time. See OCPI Spec 2.2.1."
      required: false
      schema:
        $ref: '../common/definitions.yaml#/components/schemas/DateTime'
    
    Offset:
      name: offset
      in: query
      description: "The offset of the first object returned. Default is 0. See OCPI Spec 2.2.1."
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
    
    Limit:
      name: limit
      in: query
      description: "Maximum number of objects to GET. See OCPI Spec 2.2.1."
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 100
